services:
  - type: web
    name: english-learning-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-old-bird-b3sbga0g-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&stringtype=unspecified
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_svzjQOo1Mi8I
      - key: GOOGLE_CLIENT_ID
        value: 537126281362-c176dp1e8pss19m34u3tbm83asg0dht5.apps.googleusercontent.com
      - key: AES_SECRET_KEY
        sync: false
